### ISSUE TITLE
Videos muy pequeños y cortados en el website

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5538]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/41120095?key=1d6da292920bbb9cc7e0067b565079ad&size=orig) 

 - [ ] Revisar los proyectos de los alumnos
- [ ] Revisar seccion de 3 ways in 3 stories https://www.awesomescreenshot.com/image/41120112?key=94b3358d56dca8be7bb5dfdac6539a52

**Comment by tommygonzaleza** [comment]
Haz el video un poco mas alto

**Comment by URubino4Geeks** [comment]
Todavía se ven cortados y pequeños los videos: https://dev.4geeksacademy.com/es/landing/academia-programacion



![Image](https://github.com/breatheco-de/breatheco-de/assets/129084465/cb8952fa-a6f6-460c-942a-e6b8355c6bab)

El componente es este: 

```
  - name: passion
    position: 7
    layout: two_column_right
    proportions: [6, 6]
    image:
      style: '{ "backgroundSize": "contain" }'
      src: "/images/badges/switchup-badge-2023.png"
      link: "https://www.switchup.org/bootcamps/4geeks-academy"
    video: "JLSP_1HYoAg"
    heading:
      text: "Nanutria y 4Geeks"
      font_size: ["40px", "40px", "40px", "40px", "40px"]
    content:
      text: "Nanutria tiene todas las características de una persona con la que nos identificamos en 4Geeks. Es Ingeniero, es ingenioso, es talentoso y es constante. Se decidió por la comedia pero mantiene los rasgos de lo que todos queremos poder ser, cada uno en sus áreas. Ahora Nanutria también recomienda 4Geeks Academy"
      font_size: ["16px"]
```
