### ISSUE TITLE
Mejoras al two_column_right y two_column_left

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5946]
Este es el yml actual:

```yml
  - name: new_design_with_bullets
    position: 9
    layout: two_column_right 
    swipable: False
    background: "#FFFFFF"
    image:
      style: "{}"
      src: "/images/alumni-bg.png"
      link: "https://google.com" # take uses somewhere when they click on the image
      shadow: true
    heading: 
      text: "Finance your future"
    sub_heading:
      text: "We're all about making our high-quality education affordable to everyone."
    button: 
      text: "See all financing options"
      color: white
      hover_color: "white"
      background: "black"
      path: "https://www.youtube.com/watch?v=plwPwyrxX84"
    content: 
      text: "We're all about making our high-quality education affordable to everyone. That's why we offer multiple options to help you fund our coding bootcamps stress-free. Whether it's an ISA, scholarship, payment plan or Job Guarantee we're here to guide you every step of the way."
      font_size: ["16px"]
      path: ""
    bullets:
      - Lorem ipsum dolor sit amet
      - Lorem ipsum dolor sit amet
      - Lorem ipsum dolor sit amet

```

Ahora los bullets van a tender lo siguiente:

```
    bullets:
      - heading: Lorem ipsum dolor sit amet
         text: Some text description for the bullet
         icon: string with icon for example ['check', 'cicle', etc]
      - heading: Lorem ipsum dolor sit amet
         text: Some text description for the bullet
         icon: string with icon for example ['check', 'cicle', etc]
```

Todos son opcionals, y hay queue probar bien also espaciados.

Ejemplos de como see deberia ver:

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=6835-7497&mode=design&t=lY9mhZrP4wv7pHgb-0
