### ISSUE TITLE
Nuevo layout para custom component de programas

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#5947]
- [ ] Fijate bien que va a estar dentro del arreglo de `components`.
- [ ] Por favor reutilizar el componente [ChooseYourProgram](https://github.com/4GeeksAcademy/website-v2/blob/landings/src/components/ChooseYourProgram/index.js) para no rehacer el codigo.
- [ ] Todos los landings donde se usaba `choose_your_program` ahora debe usarse `components[N].layout=choose_your_program`
- [ ] Actualiza los estilos para que se parezcan al nuevo diseño con los bordes negros.

Este va a ser el YML del componente:

```yml
components:
  name: "whatever"
  layout: choose_your_program:
  position: 5
  title: Nuestros Programas
  paragraph: Contamos con programas que combinan clases prácticas dictadas por expertos
  programs:
  - title: "Full Stack Developer"
    sub_title: "Nivel 1"
    icon: "fullstack"
    description: |
      Aprende desde cero, empezando por lo básico: HTML + CSS3 + Javascript.
      
      Aprende las habilidades más solicitadas con instructores apasionados y un plan de estudios práctico para ayudarte a encontrar un trabajo de programación como desarrollador Jr.
    
    text_link: Aplica a una beca
    link: "#"
    
  - title: "Ingeniero de Software"
    sub_title: "Nivel 2"
    icon: "software"
    description: |
      Profundizamos a un nivel avanzado principios específicos de desarrollo, llevando tu carrera a otro nivel.
      
      Texto que resuma y explique que este programa tiene modalidad part time y full time. Que también resuma eficientemente el syballus del programa. Acá incluiría un <a href="/us/apply">link</a> para poder descargar el PDF con el detalle del programa.
      Desarrolla más habilidades adentrándote en el mundo de computación y aplicaciones nativas de la nube. Aprende las habilidades que el 90% de las empresas Fortune 500 están buscando.
    
    text_link: Aplica a una beca
    link: "#"

```
