### ISSUE TITLE
Corregir propiedades del image cuando incluye video en los two_colum

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6181]
El componete [ReactPlayer](https://github.com/4GeeksAcademy/website-v2/blob/0aa4bf39588506057340f3e0abb269076725231e/src/components/ReactPlayer/index.js#L192) utiliza una image como vista previa antes de mostrar los videos.

Por otro los landings tienen en el yml la forma de espeficiar videos en un two_colum de la siguiente manera:

```yml
  - name: some_id
    position: 7
    layout: two_column_right
    image:
      src: "/images/bg/people_happy.jpg"
      shadow: true
    video: "B01-eTfgqqc"
    heading:
      text:
        "Todo lo hacemos con pasión y con la mirada puesta en tu desarrollo profesional."
        #xl      lg     md     sm    xs
      font_size: ["40px", "34px", "34px", "25px", "20px"]

````

Si te fijas en este YML estamos especificando un video pero tambien un image.
Eso es porque queremos que el image se muestre como preview del video.

La propiedad image.shadow y image.style tiene que traspasarse correctamente hasta el reactplayer.image.
