### ISSUE TITLE
Nuevo componente `<ScholarshipOptions>` para agregar los tipos de scholarships disponibles

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6814]
![Screenshot 2024-01-25 at 5 42 39 PM](https://github.com/breatheco-de/breatheco-de/assets/426452/27311159-dca5-4e1d-9689-2e751aad8670)

Se va a nutrit de un YML nuevo dentro de su carpeta de componente y se puede filtrar por location:

```yml
# file name scholarships.us.yml

- name: Veteran an military spouse
  description: Equipping our veterans with the skills and experience they need to start a new career.
  locations: ['miami-downtown', 'orlando']
  programs: ['full-stack', 'datascience-ml']
  discount: Up to $20,000 per student

- name: TechHire - OpenCode
  description: Combines a five-week training program at New York City’s LaGuardia Community College with GA’s Software Engineering Bootcamp program.
  locations: ['miami-downtown', 'orlando']
  programs: ['full-stack', 'datascience-ml']
  discount: Up to $20,000 per student

- 

```
