### ISSUE TITLE
Checkbox update

### ISSUE THREAD

**Issue by G-code7** [breatheco-de/breatheco-de#6847]
Se necesita modificar el checkbox que aparece en en el form de las landings para adaptarlo a las nuevas políticas de chile. 

![image](https://github.com/breatheco-de/breatheco-de/assets/95352419/ac8607a7-3b92-445d-a932-36a16ff51fba)

---

Basicamente, debes permitir que desde el YML del landing, se defina los checkbox que va a tener el formulario, permitiendo asi definir mas de uno. Si no estan seleccionados, el boton debe estar deshabilitado

**Comment by Khrisefzm** [comment]
PR: https://github.com/4GeeksAcademy/website-v2/pull/1936

**Comment by tommygonzaleza** [comment]
Debes poder permitir muchos y diferentes consents desde el yml de cada location, asi nos evitamos que cada consent que se agregue este hardcoded sino que su informacion va a estar definida directamente desde el yml del location.

La estructura de la lista de consents debe ser algo asi (Recuerda que debes hacerlo en el YML de cada idioma):

```yml
consents:
    - slug: gdpr_consent
      name: GDPR Consent
      message: Al completar este formulario acepto que me contacten por WhatsApp
      error_message: Debes aceptar el consent de GDPR
      link_label: Política de Privacidad
      url: /es/privacidad
    - slug: wa_consent
      name: WhatsApp Consent
      message: Al completar este formulario acepto que me contacten por WhatsApp
      error_message: Debes aceptar el consent de WhatsApp
```

Luego para saber cuales consents muestras en los forms, debes chequear en el YML del location.

Recuerda que solo el location de santiago de chile va a llevar este consent nuevo de WhatsApp, los demas debemos dejarlos solo con el de GDPR como estan actualmente (Pero con la estructura de lista)
