### ISSUE TITLE
Block list en el website

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6987]
Cada academia tendra la oportunidad de bloquear leads que esten aplicando basados en el telefono que tienen, la ciudad, etc.
- [ ] Crear un blocklist.yml para guardar los criterios
- [ ] Cada criterio tiene un `academias` arreglo con todos los alias que bloquearan esos leads.
- [ ] Los leads entrantes que cumplan estos criteriso NO SERAN CONVERSIONES.
- [ ] no disparemos tag manager.
- [ ] No mandemos el lead a brisco.

```yml
block_list_criteria:
       # each of this criterias will
    - academies: ['madrid-spain'] 
       phone_regex: +56
       country_regex: spain

```
