### ISSUE TITLE
Expand JSON-LD: Add EducationalOrganization, Course, and FAQPage schema to all bootcamp pages

### ISSUE THREAD

**Issue by OmarHG098** [breatheco-de/breatheco-de#9135]
Currently, only two pages on the site include JSON-LD structured data. Leading competitors are making use of FAQPage and EducationalOrganization schema, and these are often cited in responses from LLMs such as GPT-4 and Gemini.

- [x] Implement organization-wide EducationalOrganization schema.
- [x] Add Course and FAQPage markup to all bootcamp pages.
- [x] Ensure the following explicit properties are included where relevant: name, description, offers, timeToComplete, and a custom property jobGuarantee.
- [ ] Place all JSON-LD structured data within the first 600 characters of the page content to ensure chunking priority by LLMs and search engines.

This will enhance the site's structured data coverage and improve visibility in both search and AI-generated results.

**Comment by OmarHG098** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/2295

**Comment by alesanchezr** [comment]
tiene malo el type porque sale un url gigante

**Comment by tommygonzaleza** [comment]
El timeRequired no debe ser un valor fijo sino que se debe obtener desde el YML del curso.

Agrega en el YML de cada curso la propiedad duration en la meta_info, ejemplo con applied ai:

```yml
meta_info:
  slug: applied-ai-course   #<----URL: https://4geeksacademy.com/us/coding-bootcamps/applied-ai-course
  title: "Course in Applied Artificial Intelligence"
  description: "4Geeks Academy offers an AI training course with job guarantee. Dive into artificial intelligence and open doors to future tech careers."
  bc_slug: "applied-ai"
  template: "course-applied-ai"
  image: "/images/og-preview/applied-ai-bg.jpg"
  visibility: "visibility"
  keywords: ""
  show_in_apply: true
  redirects: ["/us/applied-ai"]
  related_clusters: ["trends-and-tech"]
  duration: "P6W" # Format ISO 8601
  ```
