### ISSUE TITLE
Crear una nueva seccion en la pagina llamada: "data/bootcamp-analysis"

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#9193]
Vamos a publicar muchos bootcamp analysis, cada uno tiene su YML y va a incluir las siguientes prioridades:

El siguiente YML puede funcionar como una base:

```yml
# bootcamp-template.yml

# ✅ Core Metadata
name: ""                                   # Full official name
slug: ""                                   # URL-safe, lowercase-hyphenated
website: ""
status: "active"                           # active | paused | closed | zombie

# 📍 Ownership & Location
ownership:
  type: ""                                 # founder-led | private-equity | university-owned | corporate
  owner_name: ""
founded_year: 0
headquarters: ""
locations:                                 # cities or remote
  - ""

# 🧠 AI Capabilities
ai_features:
  uses_ai_tutor: false
  ai_agent_name: ""
  auto_grading: false
  ai_curriculum:
    included: false
    strategy: ""                           # integrated across tracks | separate course | superficial | not included
  roles_prepared:
    - ""                                   # e.g. Prompt Engineer, AI Product Manager, etc.

# 🧑‍🏫 Educational Model
mentorship:
  has_human_mentorship: true
  mentorship_types:
    - "1:1 mentorship"
    - "Group mentoring"
  frequency: ""
cohort_model: ""                           # cohort-based | self-paced | hybrid
syllabus_update_frequency: ""
syllabus_last_updated: ""

# 🧾 Curriculum & Offerings
tracks_offered:
  - ""                                     # e.g., Full Stack Dev, Cybersecurity, Data Science
programming_languages:
  - ""                                     # Python, JavaScript, etc.
bootcamp_duration_weeks: 0
capstone_project_required: false
portfolio_development: true
certification_awarded: true
external_certifications:
  - ""                                     # e.g., Google Cloud, CompTIA, etc.

# 📚 Features (From Industry Comparison)
features:
  career_support: ""                       # e.g., "forever", "until job"
  teacher_student_ratio: ""
  response_time: ""
  one_on_one_mentoring: ""
  interview_preparation: ""
  hiring_rate: ""                          # e.g., "~84%"
  community: ""
  class_format:
    - "online"
    - "offline"
    - "hybrid"
  requires_previous_knowledge: false

# 💸 Tuition & Financing
tuition_cost_usd: 0
financing_models:
  - ""                                     # ISA, Climb, Upfront, etc.

# 📈 Operations
estimated_annual_revenue: ""
estimated_enrollment_per_year: 0
active_students: 0
number_of_instructors: 0
student_enrollment_trend: ""              # growing | stable | declining

# 🧑‍💼 Placement & Hiring
placement_support:
  active: true
  services:
    - "mock interviews"
    - "resume reviews"
    - "employer referrals"
transparency:
  average_salary_after: ""
  outcomes_verified_by_third_party: false
  cohort_size_average: 0

# 🏢 Hiring Partners
hiring_partners:
  - ""                                     # List of known companies
employer_referrals_offered: false
internal_apprenticeships: false

# 🌐 Accessibility & Flexibility
schedule_options:
  - ""                                     # Full-time, Part-time, Evening, etc.
makeup_class_policy: ""
remote_friendly: true
languages:
  - ""                                     # Course delivery languages (English, Spanish, etc.)

# 🌍 Community
community_engagement:
  platforms:
    - "Slack"
    - "Discord"
  events:
    - "Hackathons"
    - "Webinars"
  staff_access_level: ""                   # low | medium | high

# ✨ Innovation & Differentiators
innovation_highlights:
  - ""                                     # LMS, live support, gamification, etc.
bootcamp_type: ""                          # independent | franchise | university-affiliated | accelerator-based

# 🧾 Transparency
refund_policy: ""
student_reviews_public: true
glassdoor_rating: ""
trustpilot_rating: ""

# 🧑‍🔬 Research Log
research_metadata:
  researcher_name: ""
  date_collected: ""
  notes: >
    Add any insights, caveats, or inconsistencies discovered during research.

```
